#include "post_router.hpp"

std::unordered_map<std::string,
                   decltype(&post::PostHandler::process<data::User>)>
    post::PostRouter::mPostRouterMap = {
        {"school",               &post::PostHandler::process<data::School>       },
        {"user",                 &post::UserHandler::process                     },
        {"role",                 &post::PostHandler::process<data::Role>         },
        {"grade",                &post::PostHandler::process<data::Grade>        },
        {"grade_student",        &post::PostHandler::process<data::Grade_student>},
        {"group",                &post::PostHandler::process<data::Group>        },
        {"group_student",        &post::PostHandler::process<data::Group_student>},
        {"lesson",               &post::PostHandler::process<data::Lesson>       },
        {"journal_table",        &post::JournalHandler::process                  },
        {"subject",              &post::PostHandler::process<data::Subject>      },
        {"mark",                 &post::MarkHandler::process                     },
        {"plan",                 &post::PostHandler::process<data::Plan>         },
        {"theme",                &post::PostHandler::process<data::Theme>        },
        {"file",                 &post::PostHandler::process<data::File>         },
        {"safe_file",            &post::PostHandler::process<data::Safe_file>    },
        {"holiday",              &post::PostHandler::process<data::Holiday>      },
        {"competition",          &post::PostHandler::process<data::Competition>  },
        {"user_competition",
         &post::PostHandler::process<data::User_competition>                     },
        {"problem",              &post::PostHandler::process<data::Problem>      },
        {"submission",           &post::PostHandler::process<data::Submission>   },
        {"competition_problem",
         &post::PostHandler::process<data::Competition_problem>                  },
        {"question",             &post::PostHandler::process<data::Question>     },
        {"user_answer",          &post::UserAnswerHandler::process               },
        {"competition_question",
         &post::PostHandler::process<data::Competition_question>                 },
        {"question_type",        &post::PostHandler::process<data::Question_type>},
        {"file_exchange",        &post::PostHandler::process<data::File_exchange>}
};

std::unordered_map<std::string,
                   decltype(&post::PostHandler::manyToMany<data::User>)>
    post::PostRouter::mManyToManyRouterMap = {
        {"school",               &post::PostHandler::manyToMany<data::School>       },
        {"user",                 &post::PostHandler::manyToMany<data::User>         },
        {"role",                 &post::PostHandler::manyToMany<data::Role>         },
        {"grade",                &post::PostHandler::manyToMany<data::Grade>        },
        {"grade_student",        &post::PostHandler::manyToMany<data::Grade_student>},
        {"group",                &post::PostHandler::manyToMany<data::Group>        },
        {"group_student",        &post::PostHandler::manyToMany<data::Group_student>},
        {"lesson",               &post::PostHandler::manyToMany<data::Lesson>       },
        {"journal_table",        &post::PostHandler::manyToMany<data::Journal_table>},
        {"subject",              &post::PostHandler::manyToMany<data::Subject>      },
        {"mark",                 &post::PostHandler::manyToMany<data::Mark>         },
        {"plan",                 &post::PostHandler::manyToMany<data::Plan>         },
        {"theme",                &post::PostHandler::manyToMany<data::Theme>        },
        {"file",                 &post::PostHandler::manyToMany<data::File>         },
        {"safe_file",            &post::PostHandler::manyToMany<data::Safe_file>    },
        {"holiday",              &post::PostHandler::manyToMany<data::Holiday>      },
        {"competition",          &post::PostHandler::manyToMany<data::Competition>  },
        {"user_competition",
         &post::PostHandler::manyToMany<data::User_competition>                     },
        {"problem",              &post::PostHandler::manyToMany<data::Problem>      },
        {"submission",           &post::PostHandler::manyToMany<data::Submission>   },
        {"competition_problem",
         &post::PostHandler::manyToMany<data::Competition_problem>                  },
        {"question",             &post::PostHandler::manyToMany<data::Question>     },
        {"user_answer",          &post::PostHandler::manyToMany<data::User_answer>  },
        {"competition_question",
         &post::PostHandler::manyToMany<data::Competition_question>                 },
        {"question_type",        &post::PostHandler::manyToMany<data::Question_type>},
        {"file_exchange",        &post::PostHandler::manyToMany<data::File_exchange>}
};

std::unordered_map<std::string,
                   decltype(&post::PostHandler::uploadFromFile<data::User>)>
    post::PostRouter::mUploadRouterMap = {
        {"school",               &post::PostHandler::uploadFromFile<data::School>     },
        {"user",                 &post::UserHandler::uploadFromFile                   },
        {"role",                 &post::PostHandler::uploadFromFile<data::Role>       },
        {"grade",                &post::PostHandler::uploadFromFile<data::Grade>      },
        {"grade_student",
         &post::PostHandler::uploadFromFile<data::Grade_student>                      },
        {"group",                &post::PostHandler::uploadFromFile<data::Group>      },
        {"group_student",
         &post::PostHandler::uploadFromFile<data::Group_student>                      },
        {"lesson",               &post::PostHandler::uploadFromFile<data::Lesson>     },
        {"journal_table",        &post::JournalHandler::uploadFromFile                },
        {"subject",              &post::PostHandler::uploadFromFile<data::Subject>    },
        {"mark",                 &post::PostHandler::uploadFromFile<data::Mark>       },
        {"plan",                 &post::PlanHandler::uploadFromFile                   },
        {"theme",                &post::PostHandler::uploadFromFile<data::Theme>      },
        {"file",                 &post::PostHandler::uploadFromFile<data::File>       },
        {"safe_file",            &post::PostHandler::uploadFromFile<data::Safe_file>  },
        {"holiday",              &post::PostHandler::uploadFromFile<data::Holiday>    },
        {"competition",          &post::PostHandler::uploadFromFile<data::Competition>},
        {"user_competition",
         &post::PostHandler::uploadFromFile<data::User_competition>                   },
        {"problem",              &post::PostHandler::uploadFromFile<data::Problem>    },
        {"submission",           &post::PostHandler::uploadFromFile<data::Submission> },
        {"competition_problem",
         &post::PostHandler::uploadFromFile<data::Competition_problem>                },
        {"question",             &post::PostHandler::uploadFromFile<data::Question>   },
        {"user_answer",          &post::PostHandler::uploadFromFile<data::User_answer>},
        {"competition_question",
         &post::PostHandler::uploadFromFile<data::Competition_question>               },
        {"question_type",
         &post::PostHandler::uploadFromFile<data::Question_type>                      },
        {"file_exchange",
         &post::PostHandler::uploadFromFile<data::File_exchange>                      }
};

std::unordered_map<std::string, decltype(&post::PostHandler::drop<data::User>)>
    post::PostRouter::mDropRouterMap = {
        {"school",               &post::PostHandler::drop<data::School>          },
        {"user",                 &post::PostHandler::drop<data::User>            },
        {"role",                 &post::PostHandler::drop<data::Role>            },
        {"grade",                &post::PostHandler::drop<data::Grade>           },
        {"grade_student",        &post::PostHandler::drop<data::Grade_student>   },
        {"group",                &post::PostHandler::drop<data::Group>           },
        {"group_student",        &post::PostHandler::drop<data::Group_student>   },
        {"lesson",               &post::PostHandler::drop<data::Lesson>          },
        {"journal_table",        &post::PostHandler::drop<data::Journal_table>   },
        {"subject",              &post::PostHandler::drop<data::Subject>         },
        {"mark",                 &post::PostHandler::drop<data::Mark>            },
        {"plan",                 &post::PostHandler::drop<data::Plan>            },
        {"theme",                &post::PostHandler::drop<data::Theme>           },
        {"file",                 &post::PostHandler::drop<data::File>            },
        {"safe_file",            &post::PostHandler::drop<data::Safe_file>       },
        {"holiday",              &post::PostHandler::drop<data::Holiday>         },
        {"competition",          &post::PostHandler::drop<data::Competition>     },
        {"user_competition",     &post::PostHandler::drop<data::User_competition>},
        {"problem",              &post::PostHandler::drop<data::Problem>         },
        {"submission",           &post::PostHandler::drop<data::Submission>      },
        {"competition_problem",
         &post::PostHandler::drop<data::Competition_problem>                     },
        {"question",             &post::PostHandler::drop<data::Question>        },
        {"user_answer",          &post::PostHandler::drop<data::User_answer>     },
        {"competition_question",
         &post::PostHandler::drop<data::Competition_question>                    },
        {"question_type",        &post::PostHandler::drop<data::Question_type>   },
        {"file_exchange",        &post::PostHandler::drop<data::File_exchange>   }
};

std::unordered_map<std::string,
                   decltype(&post::PostHandler::rawDataInsert<data::User>)>
    post::PostRouter::mRawDataRouter = {
        {"school",               &post::PostHandler::rawDataInsert<data::School>     },
        {"user",                 &post::PostHandler::rawDataInsert<data::User>       },
        {"role",                 &post::PostHandler::rawDataInsert<data::Role>       },
        {"grade",                &post::PostHandler::rawDataInsert<data::Grade>      },
        {"grade_student",
         &post::PostHandler::rawDataInsert<data::Grade_student>                      },
        {"group",                &post::PostHandler::rawDataInsert<data::Group>      },
        {"group_student",
         &post::PostHandler::rawDataInsert<data::Group_student>                      },
        {"lesson",               &post::PostHandler::rawDataInsert<data::Lesson>     },
        {"journal_table",
         &post::PostHandler::rawDataInsert<data::Journal_table>                      },
        {"subject",              &post::PostHandler::rawDataInsert<data::Subject>    },
        {"mark",                 &post::PostHandler::rawDataInsert<data::Mark>       },
        {"plan",                 &post::PostHandler::rawDataInsert<data::Plan>       },
        {"theme",                &post::PostHandler::rawDataInsert<data::Theme>      },
        {"file",                 &post::PostHandler::rawDataInsert<data::File>       },
        {"safe_file",            &post::PostHandler::rawDataInsert<data::Safe_file>  },
        {"holiday",              &post::PostHandler::rawDataInsert<data::Holiday>    },
        {"competition",          &post::PostHandler::rawDataInsert<data::Competition>},
        {"user_competition",
         &post::PostHandler::rawDataInsert<data::User_competition>                   },
        {"problem",              &post::PostHandler::rawDataInsert<data::Problem>    },
        {"submission",           &post::PostHandler::rawDataInsert<data::Submission> },
        {"competition_problem",
         &post::PostHandler::rawDataInsert<data::Competition_problem>                },
        {"question",             &post::PostHandler::rawDataInsert<data::Question>   },
        {"user_answer",          &post::PostHandler::rawDataInsert<data::User_answer>},
        {"competition_question",
         &post::PostHandler::rawDataInsert<data::Competition_question>               },
        {"question_type",
         &post::PostHandler::rawDataInsert<data::Question_type>                      },
        {"file_exchange",
         &post::PostHandler::rawDataInsert<data::File_exchange>                      }
};
