if(FALSE)
elseif (${TASK} MATCHES "_tester" OR ${TASK} MATCHES "all")
    include(/home/user/projects/KusServer/sources/_tester/_setup.cmake)elseif (${TASK} MATCHES "core" OR ${TASK} MATCHES "all")
    include(/home/user/projects/KusServer/sources/core/_setup.cmake)elseif (${TASK} MATCHES "database" OR ${TASK} MATCHES "all")
    include(/home/user/projects/KusServer/sources/database/_setup.cmake)elseif (${TASK} MATCHES "engine" OR ${TASK} MATCHES "all")
    include(/home/user/projects/KusServer/sources/engine/_setup.cmake)elseif (${TASK} MATCHES "olymp" OR ${TASK} MATCHES "all")
    include(/home/user/projects/KusServer/sources/olymp/_setup.cmake)elseif (${TASK} MATCHES "ontology" OR ${TASK} MATCHES "all")
    include(/home/user/projects/KusServer/sources/ontology/_setup.cmake)elseif (${TASK} MATCHES "server" OR ${TASK} MATCHES "all")
    include(/home/user/projects/KusServer/sources/server/_setup.cmake)elseif (${TASK} MATCHES "string" OR ${TASK} MATCHES "all")
    include(/home/user/projects/KusServer/sources/string/_setup.cmake)elseif (${TASK} MATCHES "utility" OR ${TASK} MATCHES "all")
    include(/home/user/projects/KusServer/sources/utility/_setup.cmake)endif()
