macro(check NAME)
    if(${TASK} MATCHES ${NAME} OR ${TASK} MATCHES all)
        include(/home/user/projects/KusServer/sources/${NAME}/_setup.cmake)
        set(${NAME}_MODULES ${MODULES})
        unset(MODULES)
        unset(LIBRARIES)

        foreach(MODULE_NAME ${${NAME}_MODULES})
            include(/home/user/projects/KusServer/sources/${MODULE_NAME}/_setup.cmake)
        endforeach()       
    endif()
endmacro()

check(kernel)
check(_test)
check(database)
check(engine)
check(olymp)
check(ontology)
check(server)
