name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        build_name: ["kernel", "_test"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: setup vcpkg
        run: git clone https://github.com/Microsoft/vcpkg.git ~/vcpkg && ~/vcpkg/bootstrap-vcpkg.sh
      - name: install gtest
        run: ~/vcpkg/vcpkg install gtest
      - name: update vcpkg path
        run: |
          rm -f cmake_config.cmake
          echo 'set(VCPKG_ROOT ~/vcpkg)' > cmake_config.cmake
          echo 'set(TASK ${{matrix.build_name}})' >> cmake_config.cmake
      - name: build
        run: cmake -B build -S . && cmake --build build
      - name: run tests
        run: ./bin/${{matrix.build_name}}_test.exe
    

    

    